server:
  port: 10010 # 网关端口

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 路由网关设置
        - id: user-service # 路由id 自定义 唯一
          uri: lb://userservice
          predicates: # 路由断言 判断请求是否符合路由规则
            - Path=/user/** #路由匹配规则
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
#          filters: # order-service服务下的过滤器
#            - AddRequestHeader=D-Header, order-filter # 添加请求头
      default-filters: # 默认过滤项
        - AddRequestHeader=D-Header, default-filter # 添加请求头
      globalcors:
        add-to-simple-url-handler-mapping: true  # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost"
#              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期