spring:
  application:
    name: eureka-server
server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eager-load: # 开启饥饿加载 在项目启动时创建，降低第一次访问的耗时
    enabled: true
    clients: userservice